openapi: 3.0.0
info:
  title: Constitution-Aware Textbook QA Bot API
  version: 1.0.0
  description: API for interacting with the Constitution-Aware Textbook QA Bot.
servers:
  - url: /api/v1
paths:
  /query:
    post:
      summary: Submit a user query to the chatbot.
      operationId: submitQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserQuery'
      responses:
        '200':
          description: Successful response from the chatbot.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatbotResponse'
        '400':
          description: Invalid input provided.
        '500':
          description: Internal server error.
components:
  schemas:
    UserQuery:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          description: The natural language string of the user's question.
          minLength: 1
          maxLength: 500
        session_id:
          type: string
          description: Optional identifier for a continuous conversation session.
          nullable: true
          format: uuid
    ChatbotResponse:
      type: object
      required:
        - text
        - constitutional_compliance_status
        - cited_sources
      properties:
        text:
          type: string
          description: The natural language string of the chatbot's answer.
        constitutional_compliance_status:
          type: string
          description: Status indicating adherence to constitution.md.
          enum:
            - COMPLIANT
            - FLAGGED
            - NON_COMPLIANT
        cited_sources:
          type: array
          description: Array of references back to the original source material.
          items:
            type: object
            properties:
              document_id:
                type: string
                description: ID of the source document (e.g., textbook, constitution).
              source_metadata:
                type: string
                description: Specific metadata for citation (e.g., "Part 3 - Chapter 2 - Page 45").
            required:
              - document_id
              - source_metadata
            additionalProperties: false # Ensure no extra properties are allowed
        query_id:
          type: string
          description: ID of the original query this response is for.
          format: uuid
      additionalProperties: false # Ensure no extra properties are allowed
